[package]
name = "msfs"
version = "0.1.0"
edition = "2024"


[dependencies]
msfs_derive = { path = "../msfs_derive" }
bitflags = "1.3"

[build-dependencies]
bindgen = "0.72"
msfs_sdk = { path = "../msfs_sdk" }
cc = "1.0"